import { GNArea, GoldEvalItem, Report } from '../types';

const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60 * 1000).toISOString();

/**
 * 15 clearly labelled SYNTHETIC reports in Sinhala script, Tamil script, English,
 * and Romanized Sinhala/Tamil across Kandy, Nuwara Eliya, and Matale areas.
 * Designed so reports about the same incident merge across languages into corroborated cases.
 */
export const INITIAL_SYNTHETIC_REPORTS: Report[] = [
  // CASE 1 (Act Now - Cross-language merge: Romanized Sinhala + Tamil Script + Sinhala Script at Gelioya, Gampola Road)
  {
    id: 'R-001',
    idempotencyKey: 'seed-uuid-001',
    timestamp: minsAgo(95),
    rawText:
      '[SYNTHETIC] Gampola para Gelioya hariye pas kanda kadan watila para sampurnayen wahila. Paul 3k kotu wela innawa podi lamai ekka.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.2134,
    lng: 80.5942,
    hasPin: true,
    hasPhoto: true,
    contact: '+94 77 000 1101 (Volunteer Kasun)',
    locationSource: 'pin',
    extraction: {
      language: 'romanized_si',
      incident_type: 'trapped_people',
      place_text: 'Gampola para Gelioya hariye',
      place_english: 'Gelioya, Gampola Road',
      people_affected: 12,
      needs: ['evacuation', 'road_clearance', 'baby_supplies'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (trapped / stranded people, children / infants): enforced urgency ≥ 4',
      reason:
        'Three families with young children are trapped behind an earth slip blocking Gampola Road at Gelioya.',
      confidence_in_extraction: 0.93,
      english_translation:
        'An earth embankment has collapsed near Gelioya on Gampola Road completely blocking the road. Three families are trapped with young children.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },
  {
    id: 'R-002',
    idempotencyKey: 'seed-uuid-002',
    timestamp: minsAgo(82),
    rawText:
      '[SYNTHETIC] கெலிஓயா கம்பளை வீதியில் பாரிய மண்சரிவு. 3 குடும்பங்கள் குழந்தைகளுடன் வீடுகளுக்குள் சிக்கியுள்ளனர். வீதி முற்றாக தடைப்பட்டுள்ளது.',
    sourceType: 'GN officer',
    channel: 'web_form',
    lat: 7.2136,
    lng: 80.5944,
    hasPin: true,
    hasPhoto: false,
    contact: 'GN Officer Udunuwara East',
    locationSource: 'pin',
    extraction: {
      language: 'ta',
      incident_type: 'trapped_people',
      place_text: 'கெலிஓயா கம்பளை வீதியில்',
      place_english: 'Gelioya, Gampola Road',
      people_affected: 12,
      needs: ['evacuation', 'road_clearance'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (trapped / stranded people, children / infants): enforced urgency ≥ 4',
      reason:
        'GN officer corroborates major landslide on Gampola Road at Gelioya with three families and children trapped inside homes.',
      confidence_in_extraction: 0.97,
      english_translation:
        'Major landslide on Gelioya Gampola Road. 3 families with children are trapped inside houses. Road is completely blocked.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },

  // CASE 2 (Act Now - Sinhala Script + English corroboration in Akurana Elders Home)
  {
    id: 'R-003',
    idempotencyKey: 'seed-uuid-003',
    timestamp: minsAgo(110),
    rawText:
      '[SYNTHETIC] අකුරණ නගරයේ වතුර මට්ටම අඩි 4ක් පමණ ඉහළ ගොස් ඇත. වැඩිහිටි නිවාසයක 18 දෙනෙක් ඉහළ මාලයේ සිරවී සිටිති. බෝට්ටු සහ පානීය ජලය ඉක්මනින් අවශ්‍යයි.',
    sourceType: 'GN officer',
    channel: 'web_form',
    lat: 7.3652,
    lng: 80.6178,
    hasPin: true,
    hasPhoto: true,
    contact: 'GN Officer Akurana South',
    locationSource: 'pin',
    extraction: {
      language: 'si',
      incident_type: 'trapped_people',
      place_text: 'අකුරණ නගරයේ',
      place_english: 'Akurana',
      people_affected: 18,
      needs: ['boat_rescue', 'drinking_water', 'evacuation'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (trapped / stranded people, elderly / vulnerable): enforced urgency ≥ 4',
      reason:
        'Eighteen elderly residents are stranded on an upper floor in Akurana town with 4 feet of rising floodwater.',
      confidence_in_extraction: 0.96,
      english_translation:
        'Water levels in Akurana town have risen by about 4 feet. 18 residents in an elders home are stranded on the upper floor. Boats and drinking water are urgently needed.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },
  {
    id: 'R-004',
    idempotencyKey: 'seed-uuid-004',
    timestamp: minsAgo(98),
    rawText:
      '[SYNTHETIC] Red Cross volunteer team at Akurana main street: Pinga Oya has overflowed into commercial area. 18 elderly persons trapped upstairs near Mosque Road junction, strong current requires flat-bottom boat.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.3655,
    lng: 80.6181,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'geocoded',
    extraction: {
      language: 'en',
      incident_type: 'trapped_people',
      place_text: 'Akurana main street, Mosque Road junction',
      place_english: 'Akurana',
      people_affected: 18,
      needs: ['boat_rescue', 'evacuation'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (trapped / stranded people, elderly / vulnerable): enforced urgency ≥ 4',
      reason:
        'Volunteer team confirms 18 elderly residents stranded by strong flood currents in Akurana requiring boat evacuation.',
      confidence_in_extraction: 0.95,
      english_translation:
        'Red Cross volunteer team at Akurana main street: Pinga Oya has overflowed into commercial area. 18 elderly persons trapped upstairs near Mosque Road junction, strong current requires flat-bottom boat.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },

  // CASE 3 (Act Now - Tamil Script + Tanglish corroboration on Nawalapitiya Estate Road medical emergency)
  {
    id: 'R-005',
    idempotencyKey: 'seed-uuid-005',
    timestamp: minsAgo(75),
    rawText:
      '[SYNTHETIC] நாவலப்பிட்டி தோட்டப் பாதையில் மண் சரிவு ஏற்பட்டுள்ளது. கர்ப்பிணித் தாய் ஒருவருக்கு உடனடி மருத்துவ உதவி தேவை, வாகனம் வர முடியாது.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.0568,
    lng: 80.5339,
    hasPin: true,
    hasPhoto: false,
    locationSource: 'pin',
    extraction: {
      language: 'ta',
      incident_type: 'medical',
      place_text: 'நாவலப்பிட்டி தோட்டப் பாதையில்',
      place_english: 'Nawalapitiya Estate Road',
      people_affected: 1,
      needs: ['medical_aid', 'road_clearance'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (injury / medical trauma): enforced urgency ≥ 4',
      reason:
        'A pregnant mother in Nawalapitiya requires immediate medical evacuation while estate access road is blocked by a slip.',
      confidence_in_extraction: 0.94,
      english_translation:
        'A landslide has occurred on Nawalapitiya estate road. A pregnant mother needs immediate medical help, and vehicles cannot pass.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },
  {
    id: 'R-006',
    idempotencyKey: 'seed-uuid-006',
    timestamp: minsAgo(68),
    rawText:
      '[SYNTHETIC] Nawalapitiya estate upper division veethi mann sarivu. Garbini amma orutharukku avasara medical udavi thevai, ambulance vara mudiyathu.',
    sourceType: 'Citizen',
    channel: 'sms',
    lat: 7.057,
    lng: 80.5341,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'geocoded',
    extraction: {
      language: 'romanized_ta',
      incident_type: 'medical',
      place_text: 'Nawalapitiya estate upper division veethi',
      place_english: 'Nawalapitiya Estate Road',
      people_affected: 1,
      needs: ['medical_aid', 'road_clearance'],
      urgency: 5,
      ai_raw_urgency: 5,
      ruleAdjusted: true,
      ruleReason: 'Safety rule triggered: enforced urgency ≥ 4',
      reason:
        'Second report in Romanized Tamil confirming pregnant woman needing urgent medical transport behind Nawalapitiya estate road slip.',
      confidence_in_extraction: 0.88,
      english_translation:
        'Landslide on Nawalapitiya estate upper division road. A pregnant mother needs emergency medical help, ambulance cannot reach.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },

  // CASE 4 (Verify Fast - Single Citizen report without pin/photo, high urgency >= 4, confidence 0.25 < 0.5)
  {
    id: 'R-007',
    idempotencyKey: 'seed-uuid-007',
    timestamp: minsAgo(45),
    rawText:
      '[SYNTHETIC] Hanthana uda para langa gal පෙරළිලා ගෙයක් උඩට වැටිලා කියලා ආරංචියි. පොඩි ළමයෙක්ට තුවාලයි කියනවා, හරියටම තැන දන්නේ නෑ.',
    sourceType: 'Citizen',
    channel: 'whatsapp',
    lat: 7.2589,
    lng: 80.6295,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'text',
    extraction: {
      language: 'mixed',
      incident_type: 'landslide',
      place_text: 'Hanthana uda para langa',
      place_english: 'Hanthana Upper Slope',
      people_affected: 4,
      needs: ['search_and_rescue', 'medical_aid'],
      urgency: 5,
      ai_raw_urgency: 4,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (children / infants, injury / medical trauma): enforced urgency ≥ 4',
      reason:
        'Unverified citizen forward claims rocks fell on a house on Hanthana upper road injuring a child; exact location uncertain.',
      confidence_in_extraction: 0.72,
      english_translation:
        'Heard that boulders rolled onto a house near Hanthana upper road. They say a young child is injured, exact spot unknown.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },

  // CASE 5 (Verify Fast - Single Citizen SMS report in Singlish about Kadugannawa rockfall, urgency 4, confidence 0.35 < 0.5)
  {
    id: 'R-008',
    idempotencyKey: 'seed-uuid-008',
    timestamp: minsAgo(38),
    rawText:
      '[SYNTHETIC] Kadugannawa wanguwa hariye loku gasak saha gal කඩාගෙන පාරට වැටිලා. Bus ekak hira wela wayasaka aya innawa.',
    sourceType: 'Citizen',
    channel: 'sms',
    lat: 7.2547,
    lng: 80.5256,
    hasPin: true,
    hasPhoto: false,
    locationSource: 'pin',
    extraction: {
      language: 'mixed',
      incident_type: 'road_blocked',
      place_text: 'Kadugannawa wanguwa hariye',
      place_english: 'Kadugannawa Pass',
      people_affected: 25,
      needs: ['road_clearance', 'evacuation'],
      urgency: 4,
      ai_raw_urgency: 3,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (trapped / stranded people, elderly / vulnerable): enforced urgency ≥ 4',
      reason:
        'Single citizen report of tree and rockfall blocking Kadugannawa bend with a bus containing elderly passengers halted.',
      confidence_in_extraction: 0.84,
      english_translation:
        'A large tree and boulders have fallen onto the road near Kadugannawa bend. A bus with elderly passengers is stuck.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },

  // CASE 6 (Verify Fast - Single Citizen Tamil report about missing fisherman/herder near Nanu Oya stream, urgency 4, confidence 0.25)
  {
    id: 'R-009',
    idempotencyKey: 'seed-uuid-009',
    timestamp: minsAgo(30),
    rawText:
      '[SYNTHETIC] நானுஓயா ஆற்றுப் பகுதியில் வெள்ளம் அதிகரித்துள்ளது. ஆடு மேய்க்கச் சென்ற முதியவர் ஒருவர் மாலை முதல் காணாமல் போயுள்ளார்.',
    sourceType: 'Citizen',
    channel: 'whatsapp',
    lat: 6.9428,
    lng: 80.7429,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'geocoded',
    extraction: {
      language: 'ta',
      incident_type: 'missing_person',
      place_text: 'நானுஓயா ஆற்றுப் பகுதியில்',
      place_english: 'Nanu Oya, Nuwara Eliya',
      people_affected: 1,
      needs: ['search_and_rescue'],
      urgency: 4,
      ai_raw_urgency: 4,
      ruleAdjusted: true,
      ruleReason:
        'Safety rule triggered (elderly / vulnerable): enforced urgency ≥ 4',
      reason:
        'Single uncorroborated report of an elderly man missing near rising Nanu Oya river since evening.',
      confidence_in_extraction: 0.89,
      english_translation:
        'Flooding has increased in the Nanu Oya river area. An elderly man who went to tend goats has been missing since evening.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },

  // CASE 7 (Act Now - Cross-language Sinhala + English Agency corroboration at Peradeniya Bridge road blockage)
  {
    id: 'R-010',
    idempotencyKey: 'seed-uuid-010',
    timestamp: minsAgo(125),
    rawText:
      '[SYNTHETIC] පේරාදෙණිය පාලම අසල මහවැලි ගඟ පිටාර ගැලීම නිසා මහනුවර-කොළඹ ප්‍රධාන මාර්ගයේ එක් මංතීරුවක් ජලයෙන් යටවී ඇත. ගිලන් රථ ගමනාගමනයට බාධා.',
    sourceType: 'Agency',
    channel: 'web_form',
    lat: 7.2698,
    lng: 80.5938,
    hasPin: true,
    hasPhoto: true,
    contact: 'RDA Kandy Operations Desk',
    locationSource: 'pin',
    extraction: {
      language: 'si',
      incident_type: 'road_blocked',
      place_text: 'පේරාදෙණිය පාලම අසල',
      place_english: 'Peradeniya Bridge',
      people_affected: null,
      needs: ['road_clearance'],
      urgency: 4,
      ai_raw_urgency: 4,
      ruleAdjusted: false,
      reason:
        'Mahaweli River overflow near Peradeniya Bridge has submerged one lane of the Kandy-Colombo highway, impeding ambulance transit.',
      confidence_in_extraction: 0.96,
      english_translation:
        'Due to Mahaweli River overflowing near Peradeniya Bridge, one lane of the Kandy-Colombo main road is submerged, disrupting ambulance traffic.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },
  {
    id: 'R-011',
    idempotencyKey: 'seed-uuid-011',
    timestamp: minsAgo(115),
    rawText:
      '[SYNTHETIC] Peradeniya palama gawa wathura parata dala. Kandy Colombo main road eke wahana yanna amarui, police traffic divert karanawa.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.2701,
    lng: 80.594,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'geocoded',
    extraction: {
      language: 'romanized_si',
      incident_type: 'road_blocked',
      place_text: 'Peradeniya palama gawa',
      place_english: 'Peradeniya Bridge',
      people_affected: null,
      needs: ['road_clearance'],
      urgency: 4,
      ai_raw_urgency: 4,
      ruleAdjusted: false,
      reason:
        'Floodwater over roadway at Peradeniya Bridge forcing police traffic diversion on Kandy-Colombo road.',
      confidence_in_extraction: 0.91,
      english_translation:
        'Water has come onto the road near Peradeniya Bridge. Vehicles struggle to pass on Kandy-Colombo main road, police are diverting traffic.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },

  // CASE 8 (Watch - Shelter need at Katugastota Temple camp, urgency 3, corroborated)
  {
    id: 'R-012',
    idempotencyKey: 'seed-uuid-012',
    timestamp: minsAgo(140),
    rawText:
      '[SYNTHETIC] කටුගස්තොට පන්සලේ ආරක්ෂිත මධ්‍යස්ථානයේ පවුල් 14ක් (පුද්ගලයින් 52ක්) රැඳී සිටිති. අද රාත්‍රිය සඳහා වියළි ආහාර සහ පානීය ජල බෝතල් අවශ්‍යයි.',
    sourceType: 'GN officer',
    channel: 'web_form',
    lat: 7.3264,
    lng: 80.6231,
    hasPin: true,
    hasPhoto: false,
    contact: 'GN Officer Katugastota',
    locationSource: 'pin',
    extraction: {
      language: 'si',
      incident_type: 'shelter_need',
      place_text: 'කටුගස්තොට පන්සලේ ආරක්ෂිත මධ්‍යස්ථානය',
      place_english: 'Katugastota Bazaar',
      people_affected: 52,
      needs: ['dry_rations', 'drinking_water', 'shelter'],
      urgency: 3,
      ai_raw_urgency: 3,
      ruleAdjusted: false,
      reason:
        'Fifty-two displaced persons at Katugastota temple safety centre require dry rations and bottled drinking water for tonight.',
      confidence_in_extraction: 0.97,
      english_translation:
        '14 families (52 persons) are staying at the Katugastota temple safety centre. Dry rations and drinking water bottles are needed for tonight.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },
  {
    id: 'R-013',
    idempotencyKey: 'seed-uuid-013',
    timestamp: minsAgo(130),
    rawText:
      '[SYNTHETIC] கடுகஸ்தோட்டை விகாரை முகாமில் 52 பேர் தங்கியுள்ளனர். குடிநீர் மற்றும் உலர் உணவுப் பொருட்கள் தேவை.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.3266,
    lng: 80.6233,
    hasPin: false,
    hasPhoto: false,
    locationSource: 'geocoded',
    extraction: {
      language: 'ta',
      incident_type: 'shelter_need',
      place_text: 'கடுகஸ்தோட்டை விகாரை முகாமில்',
      place_english: 'Katugastota Bazaar',
      people_affected: 52,
      needs: ['drinking_water', 'dry_rations'],
      urgency: 3,
      ai_raw_urgency: 3,
      ruleAdjusted: false,
      reason:
        'Volunteer confirms 52 displaced people at Katugastota temple camp needing drinking water and dry rations.',
      confidence_in_extraction: 0.94,
      english_translation:
        '52 people are staying at the Katugastota temple camp. Drinking water and dry food rations are needed.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },

  // CASE 9 (Watch - Minor flooding near Rattota Bridge, Matale, urgency 2)
  {
    id: 'R-014',
    idempotencyKey: 'seed-uuid-014',
    timestamp: minsAgo(60),
    rawText:
      '[SYNTHETIC] Culvert near Rattota bridge overflowing onto main road. Water is ankle deep, vehicles moving slowly. No injuries reported.',
    sourceType: 'Agency',
    channel: 'web_form',
    lat: 7.5214,
    lng: 80.6845,
    hasPin: true,
    hasPhoto: false,
    locationSource: 'pin',
    extraction: {
      language: 'en',
      incident_type: 'flooding',
      place_text: 'Rattota bridge',
      place_english: 'Rattota, Matale',
      people_affected: null,
      needs: ['road_clearance'],
      urgency: 2,
      ai_raw_urgency: 2,
      ruleAdjusted: false,
      reason:
        'Minor ankle-deep culvert overflow near Rattota Bridge in Matale with slow-moving traffic and no injuries.',
      confidence_in_extraction: 0.95,
      english_translation:
        'Culvert near Rattota bridge overflowing onto main road. Water is ankle deep, vehicles moving slowly. No injuries reported.',
    },
    humanConfirmed: true,
    syncStatus: 'synced',
  },

  // CASE 10 (Watch - Shelter supply check in Gampola Town school, urgency 3)
  {
    id: 'R-015',
    idempotencyKey: 'seed-uuid-015',
    timestamp: minsAgo(50),
    rawText:
      '[SYNTHETIC] Gampola Zahira College camp eke paul 8k innawa. Wathura බැහැලා යනකන් අද රෑට කෑම පාර්සල් 30ක් ඕනේ.',
    sourceType: 'Volunteer',
    channel: 'whatsapp',
    lat: 7.1644,
    lng: 80.5767,
    hasPin: true,
    hasPhoto: false,
    locationSource: 'pin',
    extraction: {
      language: 'romanized_si',
      incident_type: 'shelter_need',
      place_text: 'Gampola Zahira College camp',
      place_english: 'Gampola Town',
      people_affected: 30,
      needs: ['dry_rations', 'shelter'],
      urgency: 3,
      ai_raw_urgency: 3,
      ruleAdjusted: false,
      reason:
        'Eight families sheltering at Gampola Zahira College request 30 meal packets until floodwaters recede.',
      confidence_in_extraction: 0.91,
      english_translation:
        '8 families are staying at Gampola Zahira College camp. Need 30 meal packets for tonight until the water recedes.',
    },
    humanConfirmed: false,
    syncStatus: 'synced',
  },
];

/**
 * 12 Demo Grama Niladhari (GN) areas across Kandy, Nuwara Eliya, and Matale
 * with storm baselines, observed counts in the last 2-hour window, and hazard levels.
 * Three areas (GN-01 Thawalantenne, GN-02 Kalugala, GN-03 Loolkandura) are seeded as QUIET
 * under High/Medium hazard so the Silence Radar works immediately on first load.
 */
export const INITIAL_GN_AREAS: GNArea[] = [
  {
    id: 'GN-01',
    name: 'Thawalantenne (GN-684)',
    division: 'Kotmale DS',
    district: 'Nuwara Eliya',
    lat: 7.0685,
    lng: 80.6612,
    baselinePerHour: 2.8,
    observedLastWindow: 0,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'K.M. Dharmasena',
    gnOfficerPhone: '+94 71 234 5001',
  },
  {
    id: 'GN-02',
    name: 'Kalugala Upper (GN-412)',
    division: 'Ududumbara DS',
    district: 'Kandy',
    lat: 7.3195,
    lng: 80.8764,
    baselinePerHour: 2.4,
    observedLastWindow: 0,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'H.G.Bandara',
    gnOfficerPhone: '+94 71 234 5002',
  },
  {
    id: 'GN-03',
    name: 'Loolkandura Estate (GN-519)',
    division: 'Deltota DS',
    district: 'Kandy',
    lat: 7.1452,
    lng: 80.7089,
    baselinePerHour: 2.1,
    observedLastWindow: 0,
    windowHours: 2,
    hazardLevel: 'medium',
    gnOfficerName: 'S. Thangarajah',
    gnOfficerPhone: '+94 77 234 5003',
  },
  {
    id: 'GN-04',
    name: 'Gelioya North (GN-205)',
    division: 'Udunuwara DS',
    district: 'Kandy',
    lat: 7.2134,
    lng: 80.5942,
    baselinePerHour: 3.0,
    observedLastWindow: 6,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'R.M. Jayaratne',
    gnOfficerPhone: '+94 71 234 5004',
  },
  {
    id: 'GN-05',
    name: 'Akurana Town (GN-310)',
    division: 'Akurana DS',
    district: 'Kandy',
    lat: 7.3652,
    lng: 80.6178,
    baselinePerHour: 3.5,
    observedLastWindow: 8,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'M.F. Roshan',
    gnOfficerPhone: '+94 77 234 5005',
  },
  {
    id: 'GN-06',
    name: 'Peradeniya West (GN-118)',
    division: 'Gangawata Korale DS',
    district: 'Kandy',
    lat: 7.2698,
    lng: 80.5938,
    baselinePerHour: 2.5,
    observedLastWindow: 5,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'D.M.N.Kumari',
    gnOfficerPhone: '+94 71 234 5006',
  },
  {
    id: 'GN-07',
    name: 'Nawalapitiya South (GN-702)',
    division: 'Pasbage Korale DS',
    district: 'Kandy',
    lat: 7.0568,
    lng: 80.5339,
    baselinePerHour: 2.2,
    observedLastWindow: 5,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'V.Selvaraj',
    gnOfficerPhone: '+94 77 234 5007',
  },
  {
    id: 'GN-08',
    name: 'Katugastota Bazaar (GN-291)',
    division: 'Harispattuwa DS',
    district: 'Kandy',
    lat: 7.3264,
    lng: 80.6231,
    baselinePerHour: 2.0,
    observedLastWindow: 4,
    windowHours: 2,
    hazardLevel: 'medium',
    gnOfficerName: 'A.M.Weerakoon',
    gnOfficerPhone: '+94 71 234 5008',
  },
  {
    id: 'GN-09',
    name: 'Hanthana Tea Range (GN-144)',
    division: 'Gangawata Korale DS',
    district: 'Kandy',
    lat: 7.2589,
    lng: 80.6295,
    baselinePerHour: 1.8,
    observedLastWindow: 3,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'P.G.Karunathilaka',
    gnOfficerPhone: '+94 71 234 5009',
  },
  {
    id: 'GN-10',
    name: 'Kadugannawa Pass (GN-088)',
    division: 'Yatinuwara DS',
    district: 'Kandy',
    lat: 7.2547,
    lng: 80.5256,
    baselinePerHour: 2.0,
    observedLastWindow: 4,
    windowHours: 2,
    hazardLevel: 'high',
    gnOfficerName: 'W.A.S.Perera',
    gnOfficerPhone: '+94 71 234 5010',
  },
  {
    id: 'GN-11',
    name: 'Rattota East (GN-815)',
    division: 'Rattota DS',
    district: 'Matale',
    lat: 7.5214,
    lng: 80.6845,
    baselinePerHour: 1.5,
    observedLastWindow: 3,
    windowHours: 2,
    hazardLevel: 'medium',
    gnOfficerName: 'U.G.Rathnayake',
    gnOfficerPhone: '+94 71 234 5011',
  },
  {
    id: 'GN-12',
    name: 'Kundasale New Town (GN-340)',
    division: 'Kundasale DS',
    district: 'Kandy',
    lat: 7.2839,
    lng: 80.6872,
    baselinePerHour: 1.2,
    observedLastWindow: 0,
    windowHours: 2,
    hazardLevel: 'low',
    gnOfficerName: 'N.K.Ekanayake',
    gnOfficerPhone: '+94 71 234 5012',
  },
];

/**
 * 20 Synthetic Labelled Gold Evaluation Reports:
 * - 5 Sinhala Script
 * - 5 Tamil Script
 * - 5 English
 * - 5 Romanized (Singlish / Tanglish)
 */
export const GOLD_EVALUATION_SET: GoldEvalItem[] = [
  // 5 Sinhala Script
  {
    id: 'EVAL-SI-01',
    category: 'Sinhala Script',
    rawText:
      'ගම්පොල නගරයේ නිවාස 4ක් ජලයෙන් යටවී ඇත. කුඩා දරුවන් දෙදෙනෙකු සමඟ පවුලක් වහලය මත සිරවී සිටිති. බෝට්ටුවක් අවශ්‍යයි.',
    expectedLanguage: 'si',
    expectedIncidentType: 'trapped_people',
    expectedPlaceEnglish: 'Gampola',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['boat_rescue', 'evacuation'],
  },
  {
    id: 'EVAL-SI-02',
    category: 'Sinhala Script',
    rawText:
      'කඩුගන්නාව දුම්රිය ස්ථානය අසල විශාල පස් කන්දක් කඩා වැටී මාර්ගය සම්පූර්ණයෙන්ම අවහිර වී ඇත.',
    expectedLanguage: 'si',
    expectedIncidentType: 'road_blocked',
    expectedPlaceEnglish: 'Kadugannawa',
    expectedUrgencyMin: 3,
    expectedUrgencyMax: 5,
    expectedNeeds: ['road_clearance'],
  },
  {
    id: 'EVAL-SI-03',
    category: 'Sinhala Script',
    rawText:
      'හන්තාන ඉහළ ගම්මානයේ නායයෑමක් සිදුවී නිවාස දෙකකට හානි සිදුවී ඇත. වැඩිහිටි කාන්තාවක් තුවාල ලබා ඇත.',
    expectedLanguage: 'si',
    expectedIncidentType: 'landslide',
    expectedPlaceEnglish: 'Hanthana',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['medical_aid', 'search_and_rescue'],
  },
  {
    id: 'EVAL-SI-04',
    category: 'Sinhala Script',
    rawText:
      'කටුගස්තොට විද්‍යාලයේ ආරක්ෂිත කඳවුරේ සිටින 65 දෙනෙකුට වියළි ආහාර සහ පානීය ජලය අවශ්‍ය වී තිබේ.',
    expectedLanguage: 'si',
    expectedIncidentType: 'shelter_need',
    expectedPlaceEnglish: 'Katugastota',
    expectedUrgencyMin: 2,
    expectedUrgencyMax: 4,
    expectedNeeds: ['dry_rations', 'drinking_water'],
  },
  {
    id: 'EVAL-SI-05',
    category: 'Sinhala Script',
    rawText:
      'පේරාදෙණිය ගඟ අසල පදිංචි 70 හැවිරිදි පුද්ගලයෙකු උදෑසන සිට අතුරුදහන් වී ඇත.',
    expectedLanguage: 'si',
    expectedIncidentType: 'missing_person',
    expectedPlaceEnglish: 'Peradeniya',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['search_and_rescue'],
  },

  // 5 Tamil Script
  {
    id: 'EVAL-TA-01',
    category: 'Tamil Script',
    rawText:
      'அக்குறணை பிரதான வீதியில் வெள்ளம் காரணமாக 10 முதியவர்கள் மாடியில் சிக்கியுள்ளனர். உடனடி படகு உதவி தேவை.',
    expectedLanguage: 'ta',
    expectedIncidentType: 'trapped_people',
    expectedPlaceEnglish: 'Akurana',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['boat_rescue', 'evacuation'],
  },
  {
    id: 'EVAL-TA-02',
    category: 'Tamil Script',
    rawText:
      'நாவலப்பிட்டி தோட்டப் பாதையில் மரம் விழுந்து வீதி முற்றாக தடைப்பட்டுள்ளது. வாகனங்கள் செல்ல முடியாது.',
    expectedLanguage: 'ta',
    expectedIncidentType: 'road_blocked',
    expectedPlaceEnglish: 'Nawalapitiya',
    expectedUrgencyMin: 3,
    expectedUrgencyMax: 4,
    expectedNeeds: ['road_clearance'],
  },
  {
    id: 'EVAL-TA-03',
    category: 'Tamil Script',
    rawText:
      'நானுஓயா மலைப்பகுதியில் பாரிய மண்சரிவு ஏற்பட்டுள்ளது. இரண்டு தொழிலாளர் குடியிருப்புகள் சேதமடைந்துள்ளன.',
    expectedLanguage: 'ta',
    expectedIncidentType: 'landslide',
    expectedPlaceEnglish: 'Nanu Oya',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['evacuation', 'search_and_rescue'],
  },
  {
    id: 'EVAL-TA-04',
    category: 'Tamil Script',
    rawText:
      'தலவாக்கலை முகாமில் உள்ள 40 குடும்பங்களுக்கு குடிநீர் மற்றும் குழந்தை உணவுப் பொருட்கள் அவசரமாகத் தேவை.',
    expectedLanguage: 'ta',
    expectedIncidentType: 'shelter_need',
    expectedPlaceEnglish: 'Talawakele',
    expectedUrgencyMin: 3,
    expectedUrgencyMax: 5,
    expectedNeeds: ['drinking_water', 'baby_supplies'],
  },
  {
    id: 'EVAL-TA-05',
    category: 'Tamil Script',
    rawText:
      'மடவளை பகுதியில் வெள்ளத்தில் சிக்கிய கர்ப்பிணிப் பெண்ணுக்கு உடனடி மருத்துவ உதவி தேவைப்படுகிறது.',
    expectedLanguage: 'ta',
    expectedIncidentType: 'medical',
    expectedPlaceEnglish: 'Madulkelle',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['medical_aid'],
  },

  // 5 English
  {
    id: 'EVAL-EN-01',
    category: 'English',
    rawText:
      'Two families with three young children are trapped inside a flooded house near Gelioya junction. Water rising fast, boat needed.',
    expectedLanguage: 'en',
    expectedIncidentType: 'trapped_people',
    expectedPlaceEnglish: 'Gelioya',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['boat_rescue', 'evacuation'],
  },
  {
    id: 'EVAL-EN-02',
    category: 'English',
    rawText:
      'Earth slip and fallen boulders have completely blocked the main road at Ududumbara hairpin bend.',
    expectedLanguage: 'en',
    expectedIncidentType: 'road_blocked',
    expectedPlaceEnglish: 'Ududumbara',
    expectedUrgencyMin: 3,
    expectedUrgencyMax: 4,
    expectedNeeds: ['road_clearance'],
  },
  {
    id: 'EVAL-EN-03',
    category: 'English',
    rawText:
      'Diabetic elderly patient stranded in Peradeniya needs urgent insulin and medical transport.',
    expectedLanguage: 'en',
    expectedIncidentType: 'medical',
    expectedPlaceEnglish: 'Peradeniya',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['medical_aid'],
  },
  {
    id: 'EVAL-EN-04',
    category: 'English',
    rawText:
      'Minor surface flooding across Rattota lower road. Drains clogged, water 6 inches deep, traffic passable.',
    expectedLanguage: 'en',
    expectedIncidentType: 'flooding',
    expectedPlaceEnglish: 'Rattota',
    expectedUrgencyMin: 1,
    expectedUrgencyMax: 3,
    expectedNeeds: ['road_clearance'],
  },
  {
    id: 'EVAL-EN-05',
    category: 'English',
    rawText:
      '85 evacuees at Matale Hindu College relief center need dry rations and clean drinking water for tomorrow morning.',
    expectedLanguage: 'en',
    expectedIncidentType: 'shelter_need',
    expectedPlaceEnglish: 'Matale',
    expectedUrgencyMin: 2,
    expectedUrgencyMax: 4,
    expectedNeeds: ['dry_rations', 'drinking_water'],
  },

  // 5 Romanized (Singlish / Tanglish)
  {
    id: 'EVAL-RO-01',
    category: 'Romanized (Singlish/Tanglish)',
    rawText:
      'Akurana town eke wathura adi 5k witara wadi wela. Gedara udata wela paulak kotu wela innawa podi lamai ekka, boat ekak ewanna.',
    expectedLanguage: 'romanized_si',
    expectedIncidentType: 'trapped_people',
    expectedPlaceEnglish: 'Akurana',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['boat_rescue', 'evacuation'],
  },
  {
    id: 'EVAL-RO-02',
    category: 'Romanized (Singlish/Tanglish)',
    rawText:
      'Peradeniya palama langa loku gasak kadan watila Kandy para sampurnayen wahila. Wahana yanna ba.',
    expectedLanguage: 'romanized_si',
    expectedIncidentType: 'road_blocked',
    expectedPlaceEnglish: 'Peradeniya',
    expectedUrgencyMin: 3,
    expectedUrgencyMax: 4,
    expectedNeeds: ['road_clearance'],
  },
  {
    id: 'EVAL-RO-03',
    category: 'Romanized (Singlish/Tanglish)',
    rawText:
      'Hanthana kanda paththe pas kanda kadan watila gewal 2k yata wela. Wayasaka kenekta thuwalai, ikmanin udaw ona.',
    expectedLanguage: 'romanized_si',
    expectedIncidentType: 'landslide',
    expectedPlaceEnglish: 'Hanthana',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['search_and_rescue', 'medical_aid'],
  },
  {
    id: 'EVAL-RO-04',
    category: 'Romanized (Singlish/Tanglish)',
    rawText:
      'Nawalapitiya estate veethi mann sarivu. Kuzhanthai matrum mudhiyor veetukkul sikki ullanar, avasara udavi thevai.',
    expectedLanguage: 'romanized_ta',
    expectedIncidentType: 'trapped_people',
    expectedPlaceEnglish: 'Nawalapitiya',
    expectedUrgencyMin: 4,
    expectedUrgencyMax: 5,
    expectedNeeds: ['evacuation', 'search_and_rescue'],
  },
  {
    id: 'EVAL-RO-05',
    category: 'Romanized (Singlish/Tanglish)',
    rawText:
      'Katugastota school camp eke inna minissu 45 kata bonna wathura saha wiyali ahara ikmanata ewanna.',
    expectedLanguage: 'romanized_si',
    expectedIncidentType: 'shelter_need',
    expectedPlaceEnglish: 'Katugastota',
    expectedUrgencyMin: 2,
    expectedUrgencyMax: 4,
    expectedNeeds: ['drinking_water', 'dry_rations'],
  },
];
